all:
  children:
    kubernetes:
      hosts:
        k8s-master:
          ansible_host: your_k8s_master_ip
          ansible_user: your_ssh_user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa 