apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
data:
  odoo.conf: |
    [options]
    addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
    data_dir = /var/lib/odoo
    admin_passwd = 4hu4-9weu-zg52
    db_host = odoo-db
    db_port = 5432
    db_user = odoo
    db_password = odoo
    db_name = odoo
    list_db = True
    proxy_mode = True 