apiVersion: v1
kind: Service
metadata:
  name: odoo
spec:
  type: LoadBalancer
  ports:
  - port: 8069
    targetPort: 8069
  selector:
    app: odoo
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-db
spec:
  ports:
  - port: 5432
  selector:
    app: odoo-db 