apiVersion: v1
kind: Service
metadata:
  name: odoo
spec:
  type: NodePort
  ports:
  - port: 8069
    targetPort: 8069
    nodePort: 30069
  selector:
    app: odoo
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-db
spec:
  ports:
  - port: 5432
  selector:
    app: odoo-db 