---
- name: Create namespace if not exists
  k8s:
    name: "{{ k8s_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Apply ConfigMap
  k8s:
    state: present
    src: "{{ playbook_dir }}/../../k8s/odoo-configmap.yaml"
    namespace: "{{ k8s_namespace }}"

- name: Apply PVC
  k8s:
    state: present
    src: "{{ playbook_dir }}/../../k8s/persistent-volume-claims.yaml"
    namespace: "{{ k8s_namespace }}"

- name: Deploy PostgreSQL
  k8s:
    state: present
    src: "{{ playbook_dir }}/../../k8s/postgres-deployment.yaml"
    namespace: "{{ k8s_namespace }}"

- name: Deploy Odoo
  k8s:
    state: present
    src: "{{ playbook_dir }}/../../k8s/odoo-deployment.yaml"
    namespace: "{{ k8s_namespace }}"

- name: Deploy Services
  k8s:
    state: present
    src: "{{ playbook_dir }}/../../k8s/services.yaml"
    namespace: "{{ k8s_namespace }}" 